ASP-Net-Mvc-Data/Models/Language.cs
using System;
using System.Collections.Generic;

namespace ASP_Net_Mvc_Data.Models
{
    public class Language
    {
        public int Id { get; set; }
        public string LanguageTitle { get; set; }

        public List<PersonLanguage> PersonLanguageList { get; set; }

        public Person Person { get; set; }

        public Language() { }
        public Language(string languageTitle)
        {
            LanguageTitle = languageTitle;
        }

        public Language(string languageTitle, Person person) : this(languageTitle)
        {
            Person = person;
        }

        public Language(int id, string languageTitle, Person person) :this(languageTitle, person)
        {
            Id = id;
        }
    }
}

ASP-Net-Mvc-Data/Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Net_Mvc_Data.Models;
using ASP_Net_Mvc_Data.Models.Database;
using ASP_Net_Mvc_Data.Models.Services;
using ASP_Net_Mvc_Data.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ASP_Net_Mvc_Data.Controllers
{
    public class LanguagesController : Controller
    {
        private readonly ILanguageService _languageService;
        private readonly IPeopleService _peopleService;

        public LanguagesController(ILanguageService languageService, IPeopleService peopleService)
        {
            _languageService = languageService;
            _peopleService = peopleService;
        }

        public ActionResult Index()
        {
            var result = _languageService.All();

            return View(result);
        }

        public ActionResult Create()
        {
            CreateLanguageViewModel createLanguageViewModel = new CreateLanguageViewModel();

            return View(createLanguageViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateLanguageViewModel createLanguageViewModel)
        {
            if (ModelState.IsValid)
            {
                Language language = _languageService.Add(createLanguageViewModel);

                if (language == null)
                {
                    ModelState.AddModelError("msg", "Database problems");
                    return View(createLanguageViewModel);
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(createLanguageViewModel);
            }
        }
    }
}

ASP-Net-Mvc-Data/Controllers/PersonLanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Net_Mvc_Data.Models;
using ASP_Net_Mvc_Data.Models.Services;
using ASP_Net_Mvc_Data.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ASP_Net_Mvc_Data.Controllers
{
    public class PersonLanguageController : Controller
    {
        private readonly IPeopleService _peopleService;
        private readonly IPersonLanguageService _personLanguageService;
        private readonly ILanguageService _languageService;

        public PersonLanguageController(IPeopleService peopleService, IPersonLanguageService personLanguageService, ILanguageService languageService)
        {
            _peopleService = peopleService;
            _personLanguageService = personLanguageService;
            _languageService = languageService;
        }
        
        public IActionResult Index()
        {
            var result = _personLanguageService.All();

            var result2 = _peopleService.All().PersonList
                .Select(p => new PersonLanguageViewModel
                {
                    PersonLanguageId = p.Id,
                    PersonName = p.Name,
                    ListOfLanguages = p.PersonLanguageList
                    .Select(m => m.Language.LanguageTitle)
                    .ToList()
                })
                .ToList();

            //var languagesGroupedByPerson = result.PersonLanguages.GroupBy(i => i.Language);



            //result.PeopleList.GroupBy(person => person.Id);
                

            //var result = _personLanguageService.All();
            return View(result2);
        }

        public ActionResult AddLanguageToPerson()
        {
            PersonLanguageViewModel personLanguageViewModel = new PersonLanguageViewModel();
            //PeopleViewModel peopleViewModel = new PeopleViewModel();

            var resultPeopleViewModel = _peopleService.All();

            personLanguageViewModel.PeopleList = resultPeopleViewModel.PersonList;
            personLanguageViewModel.LanguageList = _languageService.All();

            return View(personLanguageViewModel);
        }

        [HttpPost]
        public ActionResult AddLanguageToPerson(PersonLanguageViewModel personLanguageViewModel)
        {
            if (ModelState.IsValid)
            {
                PersonLanguage personLanguage = _personLanguageService.Add(personLanguageViewModel);
                return RedirectToAction(nameof(Index));
            }

            return View(personLanguageViewModel);
        }

        public ActionResult Details(int id)         //Why not Iaction?
        {
            PersonLanguageViewModel newModel = new PersonLanguageViewModel();
            var result = _personLanguageService.FindBy(id);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            newModel.PersonName = result.PersonLanguages[0].Person.Name;

            newModel.ListOfLanguages = result.PersonLanguages
                .Select(l => l.Language.LanguageTitle).ToList();

            newModel.SpokenLanguages = string.Join<string>(", ", newModel.ListOfLanguages);

            return View(newModel);
        }
    }
}

ASP-Net-Mvc-Data/Views/Languages/AddLanguageToPerson.cshtml
@model ASP_Net_Mvc_Data.Models.ViewModels.PersonLanguageViewModel
@{
    ViewData["Title"] = "AddLanguageToPerson";
}

<h3>AddLanguageToPerson</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddLanguageToPerson">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Person" class="control-label"></label>
                <select asp-for="Person.Id" class="form-control">
                    @foreach (var item in Model.PeopleList)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <select asp-for="Language.Id" class="form-control">
                    @foreach (var item in Model.LanguageList)
                    {
                        <option value="@item.Id">@item.LanguageTitle</option>
                    }
                </select>
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="AddPersonToLanguage" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to PeopleIndex</a>
</div>

ASP-Net-Mvc-Data/Views/Languages/Create.cshtml
@model ASP_Net_Mvc_Data.Models.ViewModels.CreateLanguageViewModel

<h3>CreateCountryViewModel</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LanguageTitle" class="control-label"></label>
                <input asp-for="LanguageTitle" class="form-control" />
                <span asp-validation-for="LanguageTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@*What is form-control, ModelOnly and why form-group?*@

ASP-Net-Mvc-Data/Views/Languages/Index.cshtml
@model IEnumerable<ASP_Net_Mvc_Data.Models.Language>
@*What is Ienumerable?*@
@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create">Create new language</a>
</p>

<p>
    <a asp-controller="PersonLanguage" asp-action="AddLanguageToPerson">Add language to person</a>
</p>

<p>
    <a asp-controller="PersonLanguage" asp-action="Index">View persons and their language connections</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LanguageTitle)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LanguageTitle)
                </td>
            </tr>
        }
    </tbody>
</table>