ASP-Net-Mvc-Data/Controllers/AjaxPersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASP_Net_Mvc_Data.Models;
using ASP_Net_Mvc_Data.Models.Services;
using Microsoft.Extensions.Logging;
using ASP_Net_Mvc_Data.Models.ViewModels;

namespace ASP_Net_Mvc_Data.Controllers
{
    public class AjaxPersonsController : Controller
    {
        //private IPeopleService _peopleService = new PeopleService();

        private readonly IPeopleService _peopleService;
        private readonly ICityService _cityService;
        private readonly ILogger _logger;

        public AjaxPersonsController(IPeopleService peopleService, ICityService cityService, ILogger<AjaxPersonsController> logger)
        {
            _peopleService = peopleService;
            _cityService = cityService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AjaxFindByCityOrName(string filter)
        {
            PeopleViewModel peopleViewModel = new PeopleViewModel();

            peopleViewModel.Search = filter;

           
            if (peopleViewModel.Search == null)
            {
                var allPeople = _peopleService.All();

                //Response.StatusCode = 400;

                return PartialView("_ListPersonPartialView", allPeople);
            }
            else
            {
                var newSearch = _peopleService.FindBy(peopleViewModel);
                return PartialView("_ListPersonPartialView", newSearch);
            }
        }

        //[HttpGet]
        //public IActionResult CreateForm()
        //{
        //    CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();
        //    createPersonViewModel.CityList = _cityService.All();
        //    return PartialView("_PersonCreateAjaxPartialView", createPersonViewModel);
        //}

        //[HttpPost]
        //public IActionResult AjaxCreateForm(CreatePersonViewModel personViewModel)
        //{
        //    City city = _cityService.FindBy(personViewModel.City.Id);

        //    personViewModel.City = city;


        //    if (ModelState.IsValid)
        //    {
        //        Person person = _peopleService.Add(personViewModel);

        //        return PartialView("_PersonPartialView", person);
        //    }

        //    Response.StatusCode = 400;

        //    return PartialView("_PersonCreateAjaxPartialView", personViewModel);
        //}

        //public IActionResult AjaxDelete(string id)
        //{
        //     if (_peopleService.Remove(int.Parse(id)))
        //    {
        //        return Ok();
        //    } else
        //    {
        //        return NotFound(); //404
        //    }
        //}

        //[HttpGet]           //Is this necessary for get methods?
        //public IActionResult AjaxEdit(int id)
        //{
        //    Person person = _peopleService.FindBy(id);

        //    return PartialView("_EditPersonAjaxPartialView", person);
        //}

        //[HttpPost]
        //public IActionResult AjaxEditForm(Person person, string id)
        //{
        //    CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel() {

        //        Name = person.Name,
        //        PhoneNumber = person.PhoneNumber,
        //        City = person.City
        //};

        //    if (TryValidateModel(createPersonViewModel))
        //    {
        //        Person editedPerson = _peopleService.Edit(int.Parse(id), person);

        //        return PartialView("_PersonPartialView", editedPerson);
        //    }

    //        Response.StatusCode = 400;

    //        return PartialView("_EditPersonAjaxPartialView", person);
    //    }

    //    public IActionResult AjaxNextPage(int currentPage, int numOfPages, int recordsPerPage)
    //    {
    //        PeopleViewModel allPeople = _peopleService.All();
    //        PeopleViewModel newList = new PeopleViewModel();

    //        var rangeIndex = (currentPage * recordsPerPage) - 3;

    //        var numOfListItems = allPeople.PersonList.Count;

    //        if (numOfPages > currentPage)
    //        {
    //            var endCount = recordsPerPage;
    //            var result = allPeople.PersonList.GetRange(rangeIndex, endCount);

    //            foreach (Person person in result)
    //            {
    //                newList.PersonList.Add(person);
    //            }

    //        }
    //        else
    //        { 

    //        var endCountCalc = currentPage - 1;                     //To get right amount on page 3
    //        var endCount = numOfListItems - (recordsPerPage * endCountCalc);

    //        var result = allPeople.PersonList.GetRange(rangeIndex, endCount);

    //        foreach (Person person in result)
    //        {
    //            newList.PersonList.Add(person);
    //        }
    //        }
    //        return PartialView("_ListPersonPartialView", newList);
    //    }

    //    public IActionResult AjaxPrevPage(int currentPage, int numOfPages, int recordsPerPage)
    //    {
    //        PeopleViewModel allPeople = _peopleService.All();
    //        PeopleViewModel newList = new PeopleViewModel();

    //        var rangeIndex = (currentPage * recordsPerPage) - 3;

    //        var numOfListItems = allPeople.PersonList.Count;


    //        var result = allPeople.PersonList.GetRange(rangeIndex, recordsPerPage);

    //        foreach (Person person in result)
    //        {
    //            newList.PersonList.Add(person);
    //        }

    //        return PartialView("_ListPersonPartialView", newList);
    //    }

    //    public IActionResult AjaxPage(int currentPage, int numOfPages, int recordsPerPage, int numOfPageItems)
    //    {
    //        PeopleViewModel newList = _peopleService.PageList(currentPage, recordsPerPage, numOfPageItems);

    //        return PartialView("_ListPersonPartialView", newList);
    //    }
    }
}

ASP-Net-Mvc-Data/Views/AjaxPersons/Index.cshtml
@model ASP_Net_Mvc_Data.Models.ViewModels.PeopleViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h1>Add person to list</h1>

<div class="row" id="createPersonDiv">
    <button onclick="GetCreatePersonForm('@Url.Action("CreateForm", "AjaxPersons")')" id="btn-person-create">Add Person to list</button>
</div>

<div class="row">
    <div class="col-12">
        <h3>Search on persons</h3>
        <input id="searchInput" />
        <a class="btn btn-info"
           asp-controller="AjaxPersons"
           asp-action="AjaxFindByCityOrName"
           data-target="environment-container"
           onclick="FindByCityOrName(event, '@Url.Action("AjaxFindByCityOrName", "AjaxPersons")')">Find by city or name</a>

        <div id="environment-container"></div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col">
                <h3>Name</h3>
            </div>
            <div class="col">
                <h3>Phone number</h3>
            </div>
            <div class="col">
                <h3>City</h3>
            </div>
            <div class="col">
                <h3>Action</h3>
            </div>
        </div>
        <div id="personsListDiv"></div>
        <div class="col" id="page_btn" style="visibility: hidden">
            <a class="btn btn-info"
                id="prev_page_btn"
                style="visibility: hidden"
                asp-route-id="1"
                asp-action="AjaxPrevPage"
                onclick="PrevPage(event, '@Url.Action("AjaxPrevPage", "AjaxPersons")')">Prev</a>
            <a class="btn btn-info"
               id="next_page_btn"
               style="visibility: hidden"
               asp-route-id="2"
               asp-action="AjaxNextPage"
               onclick="NextPage(event, '@Url.Action("AjaxNextPage", "AjaxPersons")')">Next</a>
            <div id="page_numbers" style="visibility: hidden">

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div id="data_num_pages">

        </div>
        <div id="data_num_items">

        </div>
    </div>
</div>


<script src="~/js/PeopleUtil.js" asp-append-version="true"></script>