ASP-Net-Mvc-Data/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Net_Mvc_Data.Models;
using ASP_Net_Mvc_Data.Models.Services;
using ASP_Net_Mvc_Data.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASP_Net_Mvc_Data.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;

        public CitiesController(ICityService cityService, ICountryService countryService)
        {
            _cityService = cityService;
            _countryService = countryService;
        }

        public ActionResult Index()                 //Why not IAction?
        {
            return View(_cityService.All());
        }

        public ActionResult Create()
        {
            CreateCityViewModel createCityViewModel = new CreateCityViewModel();
            createCityViewModel.CountryList = _countryService.All();                     //Why sending in cCVM with all? (So they can be displayed in dropdown)


            return View(createCityViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]                  //What is antiforgerytoken? "special safety for intruders"
        public ActionResult Create(CreateCityViewModel createCity)
        {
            Country country = _countryService.FindBy(createCity.Country.Id);

            //person.Name = createPerson.Name;
            //person.PhoneNumber = createPerson.PhoneNumber;
            createCity.Country = country;

            if (ModelState.IsValid)
            {
                City city = _cityService.Add(createCity);

                if (city == null)
                {
                    ModelState.AddModelError("msg", "Database problems");
                    return View(createCity);
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(createCity);
            }
        }

        public ActionResult AddCountry()
        {
            AddCountryViewModel addCountryViewModel = new AddCountryViewModel();

            addCountryViewModel.CityList = _cityService.All();
            addCountryViewModel.CountryList = _countryService.All();

            return View(addCountryViewModel);
        }

        [HttpPost]
        public ActionResult AddCountry(AddCountryViewModel addCountry)
        {
            return View(addCountry);
        }
    }
}

ASP-Net-Mvc-Data/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Net_Mvc_Data.Models;
using ASP_Net_Mvc_Data.Models.Services;
using ASP_Net_Mvc_Data.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASP_Net_Mvc_Data.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountriesController : Controller
    {
        private readonly ICountryService _countryService;

        private readonly ICityService _cityService;

        public CountriesController(ICountryService countryService, ICityService cityService)
        {
            _countryService = countryService;
            _cityService = cityService;
        }

        public IActionResult Index()
        {
            var result = _countryService.All();
            return View(result);
        }

        public ActionResult Create()
        {
            CreateCountryViewModel createCountryViewModel = new CreateCountryViewModel();
            //createCountryViewModel.CityList = _cityService.All();                      //Why sending in cCVM with all?


            return View(createCountryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]                  //What is antiforgerytoken? "special safety for intruders"
        public ActionResult Create(CreateCountryViewModel createCountry)
        {
            if (ModelState.IsValid)
            {
                Country country = _countryService.Add(createCountry);

                if (country == null)
                {
                    ModelState.AddModelError("msg", "Database problems");
                    return View(createCountry);
                }

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(createCountry);
            }
        }
    }
}

ASP-Net-Mvc-Data/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Net_Mvc_Data.Models;
using ASP_Net_Mvc_Data.Models.Services;
using ASP_Net_Mvc_Data.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ASP_Net_Mvc_Data.Controllers
{
    [Authorize]
    public class PeopleController : Controller
    {
        private readonly ICityService _cityService;
        private readonly IPeopleService _peopleService;
        private readonly ICountryService _countryService;

        public PeopleController(ICityService cityService, IPeopleService peopleService, ICountryService countryService)
        {
            _cityService = cityService;
            _peopleService = peopleService;
            _countryService = countryService;
        }

        public IActionResult Index()
        {
            var result = _peopleService.All();
            return View(result);
        }

        public ActionResult Details(int id)         //Why not Iaction?
        {
            Person person = _peopleService.FindBy(id);

            if (person == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(person);
        }

        public ActionResult Create()
        {
            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();

            createPersonViewModel.CityList = _cityService.All();



            return View(createPersonViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreatePersonViewModel createPerson)
        {
            City city = _cityService.FindBy(createPerson.City.Id);

            //person.Name = createPerson.Name;
            //person.PhoneNumber = createPerson.PhoneNumber;
            createPerson.City = city;                   // For the hook. Not fully following. 
            

            if (ModelState.IsValid)
            {
                Person addPerson = _peopleService.Add(createPerson);

                return RedirectToAction(nameof(Index));
            }
                return View(createPerson);
        }
    }
}

ASP-Net-Mvc-Data/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ASP_Net_Mvc_Data.Models;
using ASP_Net_Mvc_Data.Models.Services;
using ASP_Net_Mvc_Data.Models.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ASP_Net_Mvc_Data.Controllers
{
    public class PersonsController : Controller
    {
        //private IPeopleService _peopleService = new PeopleService();

        private readonly IPeopleService _peopleService;

        public PersonsController(IPeopleService peopleService)
        {
            _peopleService = peopleService;
        }

        public IActionResult Index()
        {
            var result = _peopleService.All();

            return View(result);
        }

        [HttpPost]
        public IActionResult Index(PeopleViewModel filter)
        {
            var result = _peopleService.FindBy(filter);

                return View(result);
        }

        [HttpPost]
        public IActionResult Create(PeopleViewModel person)
        {
            if (ModelState.IsValid)
            {
                _peopleService.Add(person.CreatePerson);

                return RedirectToAction(nameof(Index));
            }
            return View("Index", person);
        }

        public IActionResult Delete(string id)
        {
            _peopleService.Remove(int.Parse(id));

            //Testing branches
            //Testing

            return RedirectToAction(nameof(Index));
        }

       
        /*public IActionResult AjaxFindByCityOrName(string filter)
        {
            

            PeopleViewModel peopleViewModel = new PeopleViewModel();

            peopleViewModel.Search = filter;

            PeopleViewModel newSearch = _peopleService.FindBy(peopleViewModel);

            if (newSearch == null)
            {
                return NotFound(); //404
            }
            else
            {
                return PartialView("_ListPersonPartialView", newSearch);
            }
        }*/
    }
}

ASP-Net-Mvc-Data/Views/Shared/_EditPersonAjaxPartialView.cshtml
@model Person

<form onsubmit="PostEditPersonForm(event, this, @Model.Id)" asp-controller="AjaxPersons" asp-action="AjaxEditForm" asp-route-id="@Model.Id">
    <h3>Update Person information</h3>
    <label asp-for="Name"></label>
    <input asp-for="Name" value="@Model.Name" />
    <span class="text-danger" asp-validation-for="Name"></span>
    <br />
    <label asp-for="PhoneNumber"></label>
    <input asp-for="PhoneNumber" value="@Model.PhoneNumber" />
    <span class="text-danger" asp-validation-for="PhoneNumber"></span>
    <br />
    <label asp-for="City"></label>
    @*<select asp-for="City.Id">
        @foreach (var item in Model.CityList)
        {
            <option value="@item.Id">@item.CityName</option>
        }
    </select>
    <span class="text-danger" asp-validation-for="City"></span>*@
    <br />
    <input class="btn btn-success" type="submit" value="Update" />
</form>

ASP-Net-Mvc-Data/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_Net_Mvc_Data</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_Net_Mvc_Data</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="Index">Assignment 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AjaxPersons" asp-action="Index">Ajax</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Languages" asp-action="Index">Languages</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Zone</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">Sign Up</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ASP_Net_Mvc_Data - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ASP-Net-Mvc-Data/Views/Shared/_ListPersonPartialView.cshtml
@model ASP_Net_Mvc_Data.Models.ViewModels.PeopleViewModel

@if (Model.PersonList != null)
{
    @foreach (var item in Model.PersonList)
    {
        <partial name="_PersonPartialView" model="item" />
    }
}

ASP-Net-Mvc-Data/Views/Shared/_PersonCreateAjaxPartialView.cshtml
@model ASP_Net_Mvc_Data.Models.ViewModels.CreatePersonViewModel

<form onsubmit="PostCreatePersonForm(event, this)" asp-controller="AjaxPersons" asp-action="AjaxCreateForm">
    <h3>Create</h3>
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span class="text-danger" asp-validation-for="Name"></span>
    <br />
    <label asp-for="PhoneNumber"></label>
    <input asp-for="PhoneNumber" />
    <span class="text-danger" asp-validation-for="PhoneNumber"></span>
    <br />
    <label asp-for="City"></label>
    <select asp-for="City.Id">
        @foreach (var item in Model.CityList)
        {
            <option value="@item.Id">@item.CityName</option>
        }
    </select>
    <span class="text-danger" asp-validation-for="City"></span>
    <br />
    <input class="btn btn-success" type="submit" value="Create" />
</form>

ASP-Net-Mvc-Data/Views/Shared/_PersonPartialView.cshtml
@model Person

<div class="row" id="@("personid" + Model.Id)">
    <div class="col">
        <p>@Model.Name</p>
    </div>
    <div class="col">
        <p>@Model.PhoneNumber</p>
    </div>
    <div class="col">
        <p>@Model.City.CityName</p>
    </div>
    <div class="col">
        <a class="btn btn-danger"
           asp-route-id="@Model.Id"
           asp-controller="AjaxPersons"
           asp-action="AjaxDelete"
           onclick="GetDelete(event, '@Url.Action("AjaxDelete", "AjaxPersons")')">Delete</a>
        <a class="btn btn-success"
           asp-route-id="@Model.Id"
           asp-controller="AjaxPersons"
           asp-action="AjaxEdit"
           onclick="GetEdit(event, '@Url.Action("AjaxEdit", "AjaxPersons", new { id = Model.Id})')">Edit</a>
    </div>
</div>